name: Meteor CI

on: [push]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v1
    - name: Use Meteor.js
      uses: meteorengineer/setup-meteor@test
    - name: meteor npm install and test
      run: |
        meteor npm install
        meteor npm test
        echo "TEST"
      env:
        CI: true
