name: Meteor CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Meteor.js 2.0
      uses: meteorengineer/setup-meteor@test
      with:
        meteor-release: 2.0
    - name: meteor npm install and test
      run: |
        meteor npm install
        meteor npm test
        echo "TEST"
      env:
        CI: true
