name: Meteor CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Meteor.js 1.8.1
      uses: meteorengineer/setup-meteor@test
      with:
        meteor-release: 1.8.1
    - name: npm install, build, and test
      run: |
        echo "TEST"
      env:
        CI: true
